### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [ ]:
# np.array
import numpy as np

a = np.array([1,2,3,"dghsdjk"])
print(a)

In [ ]:

aE = np.array((1,2,3))
aE

In [1]:
# 2D and 3D
import numpy as np
b = np.array([[1,2,3],[4,5,6],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]
 [4 5 6]]


In [2]:
c = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
print(c)

[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]


In [3]:
# create 2 new lists height and weight
person_height = [5.2,  5.4, 4.4, 4.5, 5.6, 6]
person_weight = [81, 55, 65, 70, 45, 44]

# create 2 numpy arrays from height and weight
person_height = np.array(person_height)
person_weight = np.array(person_weight)


In [5]:
# print 'person_height' array
person_height

array([5.2, 5.4, 4.4, 4.5, 5.6, 6. ])

In [6]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [7]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [18]:
# with reshape
np.arange(16).reshape(2,8).T

array([[ 0,  8],
       [ 1,  9],
       [ 2, 10],
       [ 3, 11],
       [ 4, 12],
       [ 5, 13],
       [ 6, 14],
       [ 7, 15]])

In [ ]:
np.arange(8).reshape()

In [19]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
# np.random
np.random.random()

0.8041437888642148

In [27]:
# np.linspace
np.linspace(-10,10,30,dtype=float)

array([-10.        ,  -9.31034483,  -8.62068966,  -7.93103448,
        -7.24137931,  -6.55172414,  -5.86206897,  -5.17241379,
        -4.48275862,  -3.79310345,  -3.10344828,  -2.4137931 ,
        -1.72413793,  -1.03448276,  -0.34482759,   0.34482759,
         1.03448276,   1.72413793,   2.4137931 ,   3.10344828,
         3.79310345,   4.48275862,   5.17241379,   5.86206897,
         6.55172414,   7.24137931,   7.93103448,   8.62068966,
         9.31034483,  10.        ])

In [28]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Numpy array vs Python lists

In [29]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
#print(c)
print(time.time()-start)

2.4348888397216797


In [30]:
# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.382000207901001


In [31]:
# memory

#list
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)


89095160

In [33]:
#numpy
a = np.arange(10000000,dtype=np.int32)
sys.getsizeof(a)

40000112

### Array Attributes

In [34]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [41]:
a3 = np.arange(8).reshape(2,4)
a3

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [42]:
# ndim
a3.ndim

2

In [43]:
# shape
print(a3.shape)
a3

(2, 4)


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [44]:
# size
a2
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [45]:
# itemsize
a3


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [46]:
a3.itemsize

4

In [47]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int32


### Changing Datatype

In [48]:
# astype
a3.astype(np.int32)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### Array Operations

In [49]:
a111 = np.arange(12).reshape(3,4)
a222 = np.arange(12,24).reshape(3,4)
a111
#a222

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
# scalar operations

# arithmetic
a111 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [51]:
# relational
a222

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [52]:
a2 == 15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [53]:
arr1 = np.array([20,30,40,50])
arr2 = np.arange(4).reshape(2,2)
arr2

array([[0, 1],
       [2, 3]])

In [54]:
arr1+arr2

ValueError: operands could not be broadcast together with shapes (4,) (2,2) 

In [55]:
arr=np.array([1,2,3])*2
arr

array([2, 4, 6])

**Using Numpy with Comparison Expressions**

In [ ]:
my_array = np.array([34, 45, 67, 45, 23])

# check which elements are greater than or equal to 40
# the comparison condition gives boolean output
new_array = my_array >= 40
new_array

In [ ]:
my_array = np.array([50, 70, 67, 45, 23])
new = my_array>=45
new

In [ ]:
my_array[new]

### Array Functions

In [ ]:
# given array
my_array = np.array([5,7,8,2,4])
my_array

**sum():**<br>
sum() function adds all the values in the array and gives a scalar output.

In [ ]:
# add all the elements of 'my_array'
my_array.sum()

In [ ]:
# find minimum of 'my_array'
my_array.min()

In [ ]:
# get cube of elements of 'my_array'
np.power(my_array,3)

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

In [ ]:
# mean/median/std/var
np.var(a1,axis=1)

In [ ]:
# trigonomoetric functions
np.sin(a1)

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
#a2*a3
np.dot(a2,a3)

In [ ]:
a1

In [ ]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

<
### Concatenation of Array

In [ ]:
# concatenate two 1D arrays
array_x = np.array([11, 22, 13])
array_y = np.array([23, 22, 12])
np.concatenate([array_x, array_y])

In [ ]:
# concatenate two 1D arrays
array_1 = np.array([11, 22, 13])
array_2 = np.array([23, 22, 12])
array_z = np.array([55, 44, 33])
np.concatenate([array_1,array_2,array_z])

In [ ]:
#You can also concatenate more than two arrays at once.
array_z = np.array([23,45])
print(np.concatenate([array_x, array_y, array_z]))

**Concatenate 2D array**

In [ ]:
# create a 2D array
my_array = np.array([[1, 2, 3],
                 [4, 5, 6]])
my_array

In [ ]:
# by default concatenate() is along 'axis = 0'
np.concatenate([my_array, my_array])

In [ ]:
np.concatenate([my_array, my_array], axis=1)

**Note:** One can not concatenate the arrays with different dimensions.

### Indexing and Slicing

In [56]:
aa1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [57]:
aa1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
a2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a3


In [ ]:
a3.shape

In [ ]:
a3[0,1]

In [ ]:
a3[1,1,0]

In [ ]:
aa1

In [ ]:
a1[2:5]

In [ ]:
a2

In [ ]:
a2[0:2,1::2]

In [ ]:
a2


In [ ]:
a2[1:4,1:4]

In [ ]:
a2[1,::3]

In [ ]:
a2[0,:]

In [ ]:
a2[:,2]

In [ ]:
a2[1:,1:3]

### Reshaping

In [ ]:
# reshape
a2

In [ ]:
# Transpose
#np.transpose(a2)
a2.T

In [ ]:
a3

In [ ]:
# ravel
a3.ravel()

In [ ]:
# Create a multi-dimensional array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Use ravel() to flatten the array
flattened_arr = arr.ravel()

print(flattened_arr)


In [ ]:
arr


In [ ]:
arr.flatten()

### Stacking

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4

In [ ]:
a5

In [ ]:
np.hstack((a4,a5))

In [ ]:
# Vertical stacking
np.vstack((a4,a5))

### Splitting
Splitting is used to split the array into multiple sub-arrays. It is the opposite of concatenation, which is implemented by the functions like split(), hsplit(), and so on.

In [ ]:
# split the array into sub-arrays
array_x = np.arange(10) 


In [ ]:
array_x

In [ ]:
np.split(array_x, 2)

In [ ]:
# the split occurs at 5th and 7th indices


array_y = np.split(array_x,[4,6])
print(array_y)

In [ ]:
# split 'array_x' into 3 sub-arrays
np.split(array_x, 2)

**array_split():** It is used to split the array into sub-arrays. It takes the integer 'N' as the input for the number of splits, even if 'N' does not divide the array into sub-arrays of equal length.<br>

In [ ]:
array_x

In [ ]:
# split 'array_x' into 3 sub-arrays using 'array_split'
np.array_split(array_x, 3)

We split the array of length 8 into 3 sub-arrays; the function 'array_split()' returns <i>8 % 3 (=2)</i> sub-arrays of size <i>8//3 + 1 (=3)</i> and the rest (i.e. one sub-array) of size <i>8//3 (=2)</i>.

**vsplit():**<br>
The vsplit() function is used to split an array into multiple sub-arrays vertically.

In [ ]:
my_array = np.arange(20.0).reshape(4,5)
my_array

In [ ]:
arr=np.arange(25).reshape(5,5)
arr

In [ ]:
np.vsplit(arr,5)

In [ ]:
my_array

In [ ]:
np.vsplit(my_array, 2)

**hsplit():**<br>
The hsplit() function is used to split an array into multiple sub-arrays horizontally (column-wise).

In [ ]:
my_array = np.arange(16.0).reshape(4,4)
my_array

In [ ]:
np.hsplit(my_array, 2)

### Advanced Indexing

In [ ]:
# Normal Indexing and slicing

a = np.arange(24).reshape(6,4)
a

In [ ]:
a[1,2]

In [ ]:
a[1:3,1:3]

In [ ]:
# Fancy Indexing
a


In [ ]:
a[:,[0,2,3]]#: select all rows.[0,2,3] 0,2,3 specific column

In [ ]:
# Boolean Indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

In [ ]:
# find all numbers greater than 50
a[a > 50]

In [ ]:
# find out even numbers
a[a % 2 == 0]

In [ ]:
# find all numbers greater than 50 and are even

a[(a > 50) & (a % 2 == 0)]

### Working with mathematical formulas

In [ ]:
a = np.arange(10)
np.sin(a)

In [ ]:
# sigmoid
def sigmoid(array):
  return 1/(1 + np.exp(-(array)))


a = np.arange(100)

sigmoid(a)

In [ ]:
# mean squared error

actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

In [ ]:
def mse(actual,predicted):
  return np.mean((actual - predicted)**2)

mse(actual,predicted)

In [ ]:
# binary cross entropy
np.mean((actual - predicted)**2)

In [ ]:
actual

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [ ]:
a


In [ ]:
np.argmax(a)

In [ ]:
# np.argmin
np.argmin(a)

### np.delete()

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Delete the first row (axis=0)
result_axis0 = np.delete(arr, 2, axis=0)
result_axis0

In [ ]:
# Output:
# array([[4, 5, 6],
#        [7, 8, 9]])

# Delete the second column (axis=1)
result_axis1 = np.delete(arr, 1, axis=1)
# Output:
# array([[1, 3],
#        [4, 6],
#        [7, 9]])

# Delete multiple rows
result_multiple_rows = np.delete(arr, [0, 2], axis=0)
# Output:
# array([[4, 5, 6]])

# Delete multiple columns
result_multiple_cols = np.delete(arr, [0, 2], axis=1)
# Output:
# array([[2],
#        [5],
#        [8]])

